select MAX(__table_name) as __table_name, 
       MAX(adCostDate) as asCostDate, 
       MAX(reportType) as reportType, 
       MAX(adSourceDirty) as adSourceDirty,
       MAX(productName) as productName, 
       MAX(adCampaignName) as adCampaignName, 
       MAX(adCampaignId) as adCampaignId, 
       MAX(adCampaignType) as adCampaignType, 
       MAX(adGroupId) as adGroupId, 
       MAX(adGroupName) as adGroupName,  
       MAX(adId) as adId,
       MAX(adPhraseName) as adPhraseName, 
       MAX(adPhraseId) as adPhraseId,
       MAX(cityCode) as cityCode, 
       MAX(utmSource) as utmSource, 
       MAX(utmMedium) as utmMedium, 
       MAX(utmCampaign) as utmCampaign,
       MAX(utmTerm) as utmTerm, 
       MAX(utmContent) as utmContent,
       SUM(adCost) as adCost, 
       SUM(impressions) as impressions, 
       SUM(clicks) as clicks, 
       MAX(load_date) as load_date,
       AdCostStatHash, 
       MAX(UtmHashHash) as UtmHashHash
from travelata.hash_ad_cost_stat
group by AdCostStatHash