{{
    config(
        materialized='table',
        order_by = ('__datetime'),
        enabled=true
    )
}}
select qid,
       __datetime,
       record_source, --pod voprosom
       __id,
       --accountName    ,
       visitId,
       clientId,
       osName,
       cityName,
       --cityCode,
    --  utmMedium    ,
       utmCampaign,
       utmSourse,
    --  utmHash    ,
      serp,
      tourPage,
      hotelPage,
      checkout,
      payment,
      adSourceDirty,
    --  utmTern   ,
    --  utmContent    ,
      utmSource,   
    --  transactionId    ,
       session,
      amountSales    ,
      pageViews   ,
    --  load_date    ,
    --  AdSessionStatHash    ,
    --  AccountHash    ,
    --  YmClientHash    ,
    --  VisitHash    ,
    --  TransactionsHash    ,
    --  UtmHashHash    ,
       __table_name    ,
    --  id   , --neponatno chto
    --  utm_base_url    ,
    --  utm_utmSource    ,
    --  utm_utmMedium    ,
    --  utm_utmCampaign    ,
        crmUserId    ,
        appmetricaDeviceId    ,
        mobileAdsId    ,
    --  publisherName    ,
    --  CrmUserHash    ,
    --  AppMetricaDeviceIdHash    ,
    --  MobileAdsIdHash    ,
        sessionId    ,
        eventName    ,
        -- itemName    ,
        -- itemId    ,
    --  itemCategory    ,
    --  OsNameHash    ,
    --  CityHash    ,
        clickDateTime  ,
        --isReinstallation    ,
    --  utmTerm    ,
    --  UtmParamsHash    ,
        appSessionId    ,
        sessionStartDatetime    ,
    --   installationId    ,
    --  installationDeviceId    ,
    --  AppSessionHash    ,
        __priority  ,
    --   __is_missed ,
      __period_number  ,
     attributed_last_click_adSourceDirty    ,
     attributed_last_click_utmMedium    ,
     attributed_last_click_utmCampaign    ,
     --attributed_last_click_utmTerm   
     round(randUniform(1, 7)) as statusIn, --vremenno
     round(randUniform(8, 14)) as statusOut --vremenno
from {{ ref('attr_final_table')}}